In [1]:
import pandas as pd

In [5]:
df_books = pd.read_csv('/content/drive/MyDrive/PLATZI/Curso Básico de Manipulación y Transformación de Datos con Pandas y NumPy/bestsellers-with-categories.csv',sep=',')
df_books.head(2)
#Para serpara un archivo distinto a comas se utiliza el siguiente codigo sep='' por el digito de separación
#Header sirve para informar en que posición se encuentra el archivo, en caso de que no tenga header se coloca none.

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [3]:
def two_times(value):
    return value * 2

In [6]:
df_books['User Rating'].apply(two_times)
#Lo aplicamos a la columna de User Rating

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ...
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [7]:
df_books['User Rating2'] =df_books['User Rating'].apply(two_times)
#Podemos guardarlo en una columna nueva

In [8]:
df_books['User Rating2'] =df_books['User Rating'].apply(lambda x: x* 3)
#Se pueden crear lambda functions

In [9]:
df_books.apply(lambda x: x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis = 1)
#Apply en varias columnas con condiciones, hay que especificar a que los vamos a aplicar (filas o columnas)

0      4.7
1      9.2
2      4.7
3      9.4
4      4.8
      ...
545    9.8
546    4.7
547    4.7
548    4.7
549    4.7
Length: 550, dtype: float64